### PR TITLE
Added mmapped writing and tests

### PR DESCRIPTION
**Pull request by fhaust**
Don't know if this will be useful to anyone except for me. But this PR adds a new function `writeMMapVector` which writes a generic vector to a mmapped file.

Also includes some tests to make sure that those files can be read back via mmapped reading.

### CODE REVIEW

**Comment by copumpkin** [comment]
Looks nice! I'm happy to merge this, but I'm not really maintaining the package on hackage anymore. Would you be willing to upload the new version to hackage and add yourself as a maintainer? I'll happily give you commit access to this repo.

**Comment by fhaust** [comment]
Yeah why not ... i mean it's probably a low maintenance library with
currently zero reverse dependencies on hackage anyway.

Otoh I think it a really useful library when working with big (scientific)
datasets as a "poor mans" flat database and/or a csv replacement.

2016-08-02 15:50 GMT+02:00 Daniel Peebles <notifications@github.com>:

**Comment by fhaust** [comment]
So ... I was thinking about putting the `vector-mmap` package on Stackage
if you don't mind. To do that I need to be added to the maintainers list on
Hackage. Could you just follow the procedure here:

https://wiki.haskell.org/Taking_over_a_package

My username on Hackage is just "fho": http://hackage.haskell.org/user/fho

Kind regards,
Florian

2016-08-11 10:42 GMT+02:00 Florian Hofmann <fho@f12n.de>:

**Comment by copumpkin** [comment]
Trying to get my account re-enabled on Hackage, since I haven't logged in in ages!

**Comment by copumpkin** [comment]
@fhaust can you check if it works for you? I added you and although you don't show up on the maintainers list for the package, if I go to your user page it says that you're a maintainer of the package.

**Comment by fhaust** [comment]
Seems to work. Maybe it just took a while to propagate to the maintainers page. As I said I'll see when I find time to get this up on stackage.

**Comment by copumpkin** [comment]
Sweet, thanks!

**Pull request merged**
